### PR TITLE
add query timeout configuration option

### LINKED ISSUE #26: Increase timeout
Hi, the timeout of 15 seconds for code cells seems a bit extreme. 

I have had a look and I'm not sure if this is configurable? there are no extension settings to tweak etc?

### PR DESCRIPTION
**Pull request by cmoog**
Closes #26

### CODE REVIEW

**Comment by RedEyedDog** [comment]
Hi.. is there a reason why this was not applied to the other drivers?

**Comment by cmoog** [comment]
The query timeout is passed through to all three drivers currently supported: mysql, postgres, and mssql.

The relevant code snippets:
https://github.com/cmoog/vscode-sql-notebook/blob/0253d2f21d82da2df3ade241c0932df32354364e/src/driver.ts#L106
https://github.com/cmoog/vscode-sql-notebook/blob/0253d2f21d82da2df3ade241c0932df32354364e/src/driver.ts#L150
https://github.com/cmoog/vscode-sql-notebook/blob/0253d2f21d82da2df3ade241c0932df32354364e/src/driver.ts#L209

At the moment, none of the driver behavior is covered by automated tests, so please do open an issue if something isn't working as expected.

**Comment by RedEyedDog** [comment]
hey thanks, i didn't notice the others ;) do you know when this will be release its bugging me

**Comment by cmoog** [comment]
@RedEyedDog [v0.5.0](https://github.com/cmoog/vscode-sql-notebook/releases/tag/v0.5.0) is live!

**Comment by RedEyedDog** [comment]
@cmoog owww yes.. thanks :)

**Comment by RedEyedDog** [comment]
i can confirm this is working very nice for mssql

**Pull request merged**
