### PR TITLE
Data table extension

### PR DESCRIPTION
**Pull request by RollsChris**
Work for integrating data table extension:

File effected: 
  package.json
  controller.js

thanks

### CODE REVIEW

**Comment by RedEyedDog** [comment]
Sorry it got  confusing and found it easier to start again ;) didnt realise PR would cancel.

i think someone needs to sort the gitignore file out.. it shows a lot of build output as change.

Thanks

**Comment by cmoog** [comment]
> i think someone needs to sort the gitignore file out.. it shows a lot of build output as change.

If you run `rm -rf ./out` from the project root, everything should be cleaned up. Otherwise, try a fresh clone.

**Comment by RedEyedDog** [comment]
could just ignore them lol

**Comment by RedEyedDog** [comment]
ok yea i understand

**Comment by cmoog** [comment]
Is there a vscode api for checking whether an extension is installed? I'm wondering if we can avoid the strict requirement on this data table extension by changing our presentation behavior based on whether the user has it installed already or not...

**Comment by RedEyedDog** [comment]
I was thinking the same.. but i don't know. hold fire then and ill take a look if you like. 

I can see that.. not an issue for me really if it means we get all the other features?

I haven't really played around with it that much, I'm pushing to get it in a bit fast because I'm fed of getting what i need by running it locally lol but lets do it properly

**Comment by jwhitaker-swiftnav** [comment]
I think the VSCode notebook API allows multiple formats for a single output - if that works how I think it does, could `vscode-sql-notebook` just provide both 'text/markdown' for its own, and 'application/json' (or whatever) for DataTable? That way users can switch between the two as needed, and it wouldn't be such a big deal if DataTable is occasionally worse.

**Comment by cmoog** [comment]
Release 0.7.0 includes support for JSON cell output. It now should be possible to leverage any extension that registers a JSON media type cell renderer. Full release notes here: https://github.com/cmoog/vscode-sql-notebook/releases/tag/v0.7.0

**Pull request closed without merging**
