### PR TITLE
add support for `oracle` driver

### LINKED ISSUE #1: Add Oracle support
Would be cool if there would be support for oracledb also.

### PR DESCRIPTION
**Pull request by cmoog**
Closes #1

### CODE REVIEW

**Comment by cmoog** [comment]
Having some difficulty getting a manual testing flow setup... which underscores the need for properly automated driver tests at some point.

**Comment by cmoog** [comment]
Had some issues with cross platform dynamic linking for the oracle client. So, going to close this for now and prioritize sqlite first.

**Comment by sschneider-ihre-pvs** [comment]
😭

**Comment by tqmkim** [comment]
what is the problem reagrding "cross platform dynamic linking for the oracle client" and how could we help?

**Pull request closed without merging**
